# OWN SETTINGS:

start_angle: 0.2              # In radians
angular_velocity: 0.2         # Rate of change of angle (radians/second)
iterations: 9                 # Depth of tree (computational power required increases exponentially so be careful)
branches_per_iteration: 3     # How many branches branch off of a single branch.
length_multiplier: 0.6        # What the size of the branches is multiplied by at every junction. (Should be < 1)
line_thickness: 1.0           # How thick the lines are drawn.

# PRESETS:

# Simple tree
# start_angle: 0.2
# angular_velocity: 0.2
# iterations: 12
# branches_per_iteration: 2
# length_multiplier: 0.6
# line_thickness: 1.0

# Lots of complex patterns moving in and out, kind of looks like snowflakes.
# start_angle: 0.2
# angular_velocity: 0.2
# iterations: 5
# branches_per_iteration: 8
# length_multiplier: 0.6
# line_thickness: 0.3

# Wheel of arms that count down to 2 and back up (quite small though)
# start_angle: 0.2
# angular_velocity: 0.3
# iterations: 4
# branches_per_iteration: 15
# length_multiplier: 0.3
# line_thickness: 0.2

# Looks kind of like Serpinski triangle.
# start_angle: 2.094395
# angular_velocity: 0.0
# iterations: 9
# branches_per_iteration: 3
# length_multiplier: 0.6
# line_thickness: 1.0

# Another nice triangle fractal.
# start_angle: 1.884955592
# angular_velocity: 0.0
# iterations: 13
# branches_per_iteration: 3
# length_multiplier: 0.6
# line_thickness: 0.2
